### PR TITLE
Rudolf integration

### PR DESCRIPTION
**Pull request by lf-**
This integrates https://github.com/ubc-carnap-team/Rudolf truth trees into Carnap using a new filter.

Note that I've split this one into separate commits to keep the stuff that needs careful review separate from the bunches of mechanical changes. I think I fixed up about 30 compiler warnings with this change set.

This might need some testing with other documents and some other routes as I don't *think* the coincidental reorganizing of the JS include order that happened here should matter much, but I am not 100% confident.

image

Here's a demo document that works with these changes, that @McTano wrote:

````pandoc
Semantic Tableau Demo
========

Our team at UBC has extended the Carnap framework to support interactive proving using the semantic tableau method. By listing the initial formulas needed for a proof in a textbook page or worksheet, an instructor can insert an interactive widget for students to complete the proof.

For example, here is an exercise which shows that the set of formulas $\{P,P \rightarrow Q,\neg P\}$ is inconsistent.

```{.TruthTree .Prop}
1.1 P,P->Q,~Q
```

This is also a proof that the argument $P, P\rightarrow Q \models Q$ is valid.

We can also give the student an empty widget, and ask them to prove a truth-theoretic statement.

1.2 Prove that the following argument is valid:
> | <span class="premise"> $\neg A \lor \neg B$</span>
> | <span class="premise"> $\neg B \lor A$</span>
> | <span class="conclusion"> $\neg B$</span>
$\neg S \land P,\neg P \lor R \models R$ is valid.
```{.TruthTree .Prop}
1.2 
```

The propositional logic system **SL** used in the UBC version of the *forall x* textbook is currently supported. We plan to support Quantified (First Order) Logic (**QL** in *forall x*), as well as variations used by other textbooks.
````

### CODE REVIEW

**Comment by lf-** [comment]
Oh dear, I broke your self-hosted runner with building JS @gleachkr. It seems like the ulimit for number of files needs to be higher. I've built that exact derivation on my system before, so it does work.

Also, I removed the instruction to run `make build-ghc` in the README after doing some hacking on the Makefile and confirming that just `make run` works fine from a fresh checkout.

**Comment by gleachkr** [comment]
No problem. It's in an nspawn container, and `ulimit -n` is locked down (I don't know if nix ordinarily adjusts ulimits, but that'd explain why it builds in other environments). Bumping the limit to 8192 worked.

**Comment by McTano** [comment]
Awesome, Jade. Thanks for taking care of this.

**Comment by gleachkr** [comment]
OK, did some testing over here. Looks good! Rearranging the include order for JS actually only changed things minimally, yesod seems to be smart about where it puts the script tags.

There is one issue I've noticed so far: `lib.css` seems to style some standard elements globally (like `input`), which breaks things like the fonts used in `proof.css`.

One thought would be to scope the Rudolph css as much as possible to the proof tree widget - if you want to get fancy, there's the Shadow DOM, but it would probably also be fine to just scope everything to a class. @McTano, @lf- Thoughts?

**Comment by McTano** [comment]
Thanks for checking it out. I'll fox the CSS classes. I think if apply them
to the react components instead of as vanilla css it will scope them
automatically. I might have to remove the bootstrap css styles too, because
they apply some different defaults to buttons and stuff. I should have a
fix in a few hours.

**Comment by lf-** [comment]
@gleachkr I've updated the version of Rudolf to the version where this CSS issue should be resolved.

**Pull request merged**
