### PR TITLE
Makefile & dev instructions

### LINKED ISSUE #104: Document and automate build process
- [ ] document the basic build process using stack, for those who can figure out how to install GHCJS.
- [ ] document the build process using the Carnap-Builder container.
- [ ] automate the steps in the process that can be automated.

For now, details can be found here:

https://groups.google.com/d/topic/carnap-users/bAQOlV4rhY0

### PR DESCRIPTION
**Pull request by lf-**
I figured out how to build the project with relatively simple/reproducible-by-others steps. This is not really idiomatic with how Nix is supposed to be used, but it builds in the "right now". I think at some point I will revisit this process to make it use an isolated Nix environment and be truly automated (not require any package installation), but for now this fixes the immediate issue.

I suppose it also fixes #104.

This change set includes and more or less requires #117 since non-dev builds won't work without the (undocumented here) SecureStrings.

### CODE REVIEW

**Comment by lf-** [comment]
This also might introduce a dependency on cabal 3.x as the paths for the GHCJS output were moved. I am not 100% sure on this.

**Comment by McTano** [comment]
@gleachkr 
Since there's no README currently, maybe these instructions could be it. What do you think?

**Comment by McTano** [comment]
It seems that `make build-client` fails or succeeds at the `AllActions` stage depending on how much memory I have available.

Maybe it's worth adding a note about memory requirements and a suggestion to close other apps if it fails with that error. @lf- you said you saw someone say on the newsgroup that 10GB of memory is required? That tracks with my observations.

**Comment by McTano** [comment]
Something else I've noticed:
When I change a file in the core `Carnap` folder, and run the make commands again, `build-server` notices that the file has changed, but `build-client` doesn't do anything because the `client-build.done` file exists.


It would be good to explain in the instructions that you need to remove this file to get the code to build again with the changes.

**Comment by lf-** [comment]
@McTano With the client build I inadvertently pessimized it for cases of working on the client as cabal took like 10 seconds to notice that nothing needed building, leading me to do that check in make, but I screwed it up. I believe it is fixed now. It also now only runs `cabal update` on full rebuilds, saving about 3-5 seconds on every client build.

Thanks for the suggestion to move the build docs to a README. I've implemented it.

I just watched a system monitor during a client build and I can confirm that it uses somewhere between 10 and 11 GiB during linking. People with small computers beware I guess ;-) a note has been added accordingly.

**Comment by lf-** [comment]
Can someone check if Apple's `make` builds this properly? I know they have a track record of shipping ancient GNU utilities and I'm wondering if their `make` is new enough to build this.

Edit: heard rumours of them shipping version 3.81 which is unfortunate since we use RECIPEPREFIX, added in 3.82. I may have to add instructions to use homebrew or bite the bullet and use Nix to fix this.

**Comment by lf-** [comment]
I'm marking this as draft as while it is very useful to get working properly right now, I am actively learning Nix and it is likely going to be superseded or significantly changed, perhaps even this weekend (I am shaving a yak on the thing I'm actually trying to do, which is to dockerize Carnap).

**Comment by gleachkr** [comment]
I look forward to the final version - this is going to be really useful, thanks for working on it!

Would it make sense, in the meantime, for me to try to review/merge #117?

**Comment by lf-** [comment]
@gleachkr yes, #117 is good to go and will be useful for Nix as well.

**Comment by lf-** [comment]
#135 supercedes this.

**Pull request closed without merging**
