### PR TITLE
Nix

### PR DESCRIPTION
**Pull request by lf-**
## Goals of using Nix:
- Improve developer experience by eliminating headaches around downloading compilers and ensure everyone has the same build environment.
- Make it easier and faster to compile Carnap for new contributors by eliminating the necessity to compile libraries.
- Unify the build environment for Carnap client-side and server-side parts.
- Enable new build-related projects such as CI and Docker images.
- Allow users to avoid Stack encoding bugs by not using Stack ;-)

## What this PR includes:
- Document using Nix to build and develop with Carnap in a comprehensive README. Also includes build infrastructure maintainer information.
- Provide a Cachix for Carnap packages.
- Nix files for the Carnap-GHCJS JavaScript target and Carnap-Server
- Pinned `nixpkgs` version that cannot change under our feet.

## Notes:

This will slightly break unmodified current non-Nix uses by moving
the symbolic link for client files to `client-out` from `dist`. The existing
Stack workflow should still work.

It does not build Carnap-GHCJS under GHC, which is unfortunate for the client development experience. The reason for this is that our `ghcjs-dom`, `0.2.4.0`, is from 2016 and its GUI dependencies on native platforms are out of support. I have tried updating it to see what happens but it is going to need code fixes.

I wrote a blog post on the Carnap nix implementation, which includes discussion of its internals: https://lfcode.ca/blog/nix-and-haskell

TODO (in a later PR): Package the book with Nix and dockerize Carnap

### CODE REVIEW

**Comment by lf-** [comment]
If it's helpful, I can organize a video chat about this implementation. Nix took a while for me to learn and I don't know if I adequately got everything through on the README, especially with how to extend it for any future use cases and do maintenance :)

**Comment by gleachkr** [comment]
Thanks - yes, that might be a good idea. Lemme read the blog post and set this up locally first.

**Comment by gleachkr** [comment]
This is looking superb. I've got everything building on my end. I posted a few minor nits in the matrix chat. Once those are sorted, I think we can merge and send it out to the relevant discussion on the mailinglist for some additional testing.

**Comment by gleachkr** [comment]
OK, I think this is good to go. Thank you for putting this together!

**Pull request merged**
