### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lf-**
Also workaround persistent not properly disabling foreign keys while
migrating sqlite databases, so sqlite migrations will actually work
properly instead of doing foreign key errors!!

~~This is probably not currently mergeable because it is not possible to get a stackage LTS with ghc 8.8.4 and new enough `persistent` (min 2.12.x to allow dropping persistent-template which was absorbed then), and we had issues with GHC 8.10, and 8.10.5 that might fix those issues is not out yet :/~~

~~It builds and runs fine with Nix and ghc-8.8.4 though (well, after a very long time of building every dependency under the sun because the default ghc got moved to 8.10).~~

~~Another of these PRs. Sorry...~~

Good to go!!

### CODE REVIEW

**Comment by lf-** [comment]
rebased

**Comment by gleachkr** [comment]
Thanks! I'll look this over and try to merge tomorrow.

**Comment by gleachkr** [comment]
OK, server updates seem good to go. The runMigrationPool thing is going to be handy! I'm running into some trouble with the nix/ghcjs component. Running

```
nix-shell --arg ghcjs true --run "make build-ghcjs" --show-trace
```
gives me
```
error: while evaluating the attribute 'buildInputs' of the derivation 'ghc-shell-for-packages-0' at /nix/store/v7zrh7whlpj7dnjvvcx7sfd6idjiiqhf-nixpkgs-stable-src/pkgs/development/haskell-modules/generic-builder.nix:615:16:
while evaluating 'getOutput' at /nix/store/v7zrh7whlpj7dnjvvcx7sfd6idjiiqhf-nixpkgs-stable-src/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /nix/store/v7zrh7whlpj7dnjvvcx7sfd6idjiiqhf-nixpkgs-stable-src/pkgs/stdenv/generic/make-derivation.nix:142:17, called from undefined position:
while evaluating the attribute 'haskell.packages.ghc8106' at /home/graham/Carnap/nix/compose-haskell-overlays.nix:15:7:
while evaluating the attribute 'haskell.packages.ghc8106.override' at /nix/store/qa7sprz3gsyj84xs0idn2l0ivp6zn19x-nixpkgs-src/pkgs/top-level/haskell-packages.nix:128:3:
attribute 'ghc8106' missing, at /home/graham/Carnap/nix/compose-haskell-overlays.nix:15:21
```

**Comment by lf-** [comment]
huh, that's weird. I'll look into it

**Comment by lf-** [comment]
I can't reproduce that on the tip of update-deps. That said, I can see a definite potential problem where the old version of nixpkgs used for ghcjs doesn't have the ghc version used by the tools, so I have tried a patch to fix that.

It seems that it will not be possible to update to ghcjs 8.10 since it is totally unusable: https://github.com/NixOS/nixpkgs/issues/172802. It seems that we are going to be sitting on ancient tech debt regarding that for the foreseeable future :/

**Comment by gleachkr** [comment]
Regrettable. Oh well. Thanks for keeping on top of that issue.

C'mon Asterius...

I'll give this a try tomorrow.

**Comment by gleachkr** [comment]
OK, I've got this up and running (the nix issue was me failing to copy some files into my development environment, derp).

I noticed something that I wanted to check with you about. At least running in development mode, I'm seeing a pretty severe performance regression on loading the instructor page and calculating grades for any number of students. Here are two logs from `top -b` of five seconds including the instructor page load and no other interactions: `top-1.log` is the main branch and `top-2.log` is the PR.

I'll see if I can tweak the -O flags for development to resemble production, in hopes that this optimizes away.

[top-2.log](https://github.com/Carnap/Carnap/files/8845879/top-2.log)
[top-1.log](https://github.com/Carnap/Carnap/files/8845880/top-1.log)

**Comment by gleachkr** [comment]
OK. I'm still seeing this with -O2. Are you able to reproduce by any chance? 

This seems to show up as soon as you navigate to the instructor page, so long as you have students whose grades are being calculated from, say, 10 or more assignments - it's got something to do with the `/instructor/*/query/` route.

**Comment by lf-** [comment]
hm. I don't know how to debug haskell performance without doing significant setup. I can say that we were using Carnap for the past few terms with this patch without issues bad enough to draw complaints.

Looking at the code for that route, a few things jump out at me based on my recent yesod training. One is that there's a new transaction being created for each assignment times each student, which is probably not helping; it would likely improve performance to lift out the runDB into an outer loop.

From a broader perspective though, the issue here may be the client side join which is doing lots of repeated work. My suggestion is probably to get out esqueleto (note: use the experimental syntax) and write a query to get the scores for every student right out of the database in one shot (may require changing how the table works to do groups instead of singles. or we could write a better query and see if that alone improves it). I acknowledge the perf issue is probably something funny ghc did, but we can likely make the database fetch an order of magnitude faster independently from ghc funny business by handing the work to the database. 

I can see if I can bang out a starting point for a query in the very limited time I have for working on Carnap.

**Comment by gleachkr** [comment]
>  I can say that we were using Carnap for the past few terms with this patch without issues bad enough to draw complaints.

OK, good to know - that puts me more at-ease. It doesn't look like there's significant memory pressure, so I think the main risk here is making things slow when multiple instructors are using the site, rather than getting OOMed.

> Looking at the code for that route, a few things jump out at me based on my recent yesod training. One is that there's a new transaction being created for each assignment times each student, which is probably not helping; it would likely improve performance to lift out the runDB into an outer loop.
> 
> From a broader perspective though, the issue here may be the client side join which is doing lots of repeated work. My suggestion is probably to get out esqueleto (note: use the experimental syntax) and write a query to get the scores for every student right out of the database in one shot (may require changing how the table works to do groups instead of singles. or we could write a better query and see if that alone improves it). I acknowledge the perf issue is probably something funny ghc did, but we can likely make the database fetch an order of magnitude faster independently from ghc funny business by handing the work to the database.

There's very likely some low-hanging fruit there  - the current implementation is pretty naive.

> I can see if I can bang out a starting point for a query in the very limited time I have for working on Carnap.

Thank you! If it turns out to be infeasible to work on this, just say so and we can unblock the PR. But if it's possible to get this merged without the performance hit, that'd be tremendous.

**Comment by lf-** [comment]
I have had a go. Let me know if it helps. It's also possible the perf issue is somewhere else. I am really flying blind.

**Comment by gleachkr** [comment]
I think that helped a little, but it's not quite back to baseline. I'm going to tinker a little. I think there might be some things that we can cache, and it definitely seems possible to push more of this transaction down below `runDB`.

**Comment by lf-** [comment]
It would be very useful to have actual instrumentation of what's going on. OpenTelemetry for Persistent and Yesod could let you dump out a trace file to look at in the Chrome trace viewer which will show good info of what's happening, but that's a implementation project I can't take on. 

I believe that caching is unnecessary and that it should be quite possible to return fresh data every request by getting rid of the most wasteful queries, however I don't have time to implement it.

**Comment by gleachkr** [comment]
OK, I got it. I apologize, it's very silly. The upgrade triggered a database migration that seems to have removed some DB indices that I had created manually. With the indices restored, we're back to baseline. That's the only blocker, so I think we're good to go. Should the esqueleto be left in, or should I merge from the prior commit?

**Comment by lf-** [comment]
I feel like we probably should keep the esqueleto because it is an improvement in code quality and potentially useful to understand how to write more esqueleto if there's more db related perf issues.

**Pull request merged**
