### PR TITLE
Move Gamma to left side in IchikawaJenkins sequent rules

### PR DESCRIPTION
**Pull request by McTano**

### CODE REVIEW

**Review by McTano — COMMENTED** [review]
I've tried this out with the Rudolf widget and everything seems to work as expected.

**Comment by McTano** [comment]
Actually, I think the order does need to be reversed on those few rules you highlighted in the matrix chat. I'll make the change and test it.

**Comment by McTano** [comment]
I reverted to the original order where "phin 1" is always first, and everything seems to work.

**Comment by gleachkr** [comment]
Looks good! Thanks for the testing. Since everything is working well, I'll start to move ahead with merging monoid unification into the main branch.

**Pull request merged**
